HM_DAO3
grom4er/taxi_service pull request #1
Opened 2021-01-12 12:45 UTC by grom4er

Create my representation of task https://mate-academy.github.io/jv-program-fulltime/02_jdbc/homework/03_dao_service_HW.html

2021-01-12 13:03 UTC, Ketch92 requested changes

2021-01-12 13:03 UTC, Ketch92 commented on src/main/java/taxiservice/models/Car.java
> +        id = Integer.toUnsignedLong(Storage.getManufactureStorage().size() + 1);
not sure if your id will be == to carId
якщо що, id карів не міняється коли ти видаляєш знизу списку, а індекси зсуваються, так може виникнути колізія ідок у машин, якщо звісно при кожному видаленні машини ти не перевизначаєш їм ід.

2021-01-12 13:03 UTC, Ketch92 commented on src/main/java/taxiservice/models/Car.java
> +        id = Integer.toUnsignedLong(Storage.getManufactureStorage().size() + 1);
плюс, присвоювати конкретний ід має БД, а в тебе прямо при ініціалізації

2021-01-12 13:03 UTC, Ketch92 commented on src/main/java/taxiservice/models/Driver.java
> +        id = Integer.toUnsignedLong(Storage.getManufactureStorage().size() + 1);
the same

2021-01-12 13:20 UTC, Ketch92 approved these changes

2021-01-12 14:37 UTC, Sofasmile requested changes

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/dao/Dao.java
> +public interface Dao<T> {
```suggestion
public interface GenericDao<T> {
```

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/dao/ManufacturerDaoImpl.java
> +@DaoImpl
```suggestion
@Dao
```

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/dao/ManufacturerDaoImpl.java
> +                        .set(element.getId().intValue(), element));
id не співпадає з позицією елемента в лісті, метод працює не валідно

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/lib/ServiceImpl.java
> +public @interface ServiceImpl {
```suggestion
public @interface Service {
```

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/service/Service.java
> +public interface Service<T> {
```suggestion
public interface GenericService<T> {
```

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureService.java
> +    @Override
should we use Override here?

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureServiceImpl.java
> +                () -> new RuntimeException(String.format("%d not found", id)));
```suggestion
                () -> new RuntimeException(String.format("Manufacturer by %d not found", id)));
```

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureServiceImpl.java
> +        return this.manufacture.update(manufacturer);
```suggestion
        return manufacture.update(manufacturer);
```

2021-01-12 14:37 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureServiceImpl.java
> +    private ManufacturerDao manufacture;
```suggestion
    private ManufacturerDao manufactureDao;
```

2021-01-13 08:53 UTC, Sofasmile requested changes

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/dao/ManufacturerGenericDao.java
> +public interface ManufacturerGenericDao extends GenericDao<Manufacturer> {
```suggestion
public interface ManufacturerDao extends GenericDao<Manufacturer> {
```

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/dao/ManufacturerGenericDaoImpl.java
> +public class ManufacturerGenericDaoImpl implements ManufacturerGenericDao {
```suggestion
public class ManufacturerDaoImpl implements ManufacturerDao {
```

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/dao/ManufacturerGenericDaoImpl.java
> +                        .set(element.getId().intValue()-1, element));
що буде, якщо ми додамо 5 елементів і список, потім видалимо другий і третій наприклад. і потім змінимо п'ятий і викличемо для нього метод update()

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/lib/GenericService.java
> +public @interface GenericService {
```suggestion
public @interface Service {
```

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/lib/Injector.java
> +                        && (clazz.isAnnotationPresent(GenericService.class)
```suggestion
                        && (clazz.isAnnotationPresent(Service.class)
```

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureService.java
>  public interface ManufactureService extends Service<Manufacturer> {
```suggestion
public interface ManufactureService extends GenericService<Manufacturer> {
```

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureService.java
>      Manufacturer create(Manufacturer manufacturer);
якщо такі методи уже є в GenericService, чи потрібно їх повторювати ще й в цьому інтерфейсі?

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureServiceImpl.java
> +@GenericService
```suggestion
@Service
```

2021-01-13 08:53 UTC, Sofasmile commented on src/main/java/taxiservice/service/ManufactureServiceImpl.java
> +        return this.manufactureDao.create(manufacturer);
```suggestion
        return manufactureDao.create(manufacturer);
```

2021-01-13 10:47 UTC, Sofasmile approved these changes
можна мержити ПР і приступати до наступної дз

2021-01-13 10:48 UTC, merged