Create and fill login controller
grom4er/taxi_service pull request #10
Opened 2021-01-25 07:37 UTC by grom4er

2021-01-25 10:25 UTC, Max-Pochepets approved these changes
fix travis :)

2021-01-25 10:25 UTC, Max-Pochepets commented on src/main/java/taxiservice/web/filters/AuthenticationFilter.java
> +        if (driverId == null || driverService.get(driverId) == null){
paragraph 5 [checklist](https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/09_filters_checklist.html)

2021-01-25 10:25 UTC, Max-Pochepets commented on src/main/webapp/WEB-INF/drivers/create.jsp
> +    Driver password number:<input type="text" name="pwd">
the password, while typed, could be seen. can we fix it?

2021-01-25 10:25 UTC, Max-Pochepets commented on src/main/webapp/WEB-INF/drivers/create.jsp
> +    Driver password number:<input type="text" name="pwd">
as well as blank input

2021-01-25 10:25 UTC, Max-Pochepets commented on src/main/webapp/WEB-INF/drivers/login.jsp
> +    Driver password :<input type="text" name="pwd">
same

2021-01-25 17:22 UTC, RomanDubovskyi requested changes
don't forget to fix points, I mentioned in the generate chat

2021-01-25 17:22 UTC, RomanDubovskyi commented on src/main/java/taxiservice/web/filters/AuthenticationFilter.java
> +        if (driverService.get(driverId) == null) {
it can't be null, it either exists, or you will get NoSuchElementException

2021-01-26 08:06 UTC, RomanDubovskyi requested changes

2021-01-26 08:06 UTC, RomanDubovskyi commented on src/main/java/taxiservice/web/filters/AuthenticationFilter.java
> +        if (driverService.get(driverId) == null) {
what about this comment?

2021-01-26 08:06 UTC, RomanDubovskyi commented on src/main/java/taxiservice/web/filters/AuthenticationFilter.java
> +    private static final Set<String> ALLOWED_URL = new HashSet<>();
```suggestion
    private static final Set<String> allowedUrls = new HashSet<>();
```
it's not a constant (not deeply immutable, the same situation as with injector)

2021-01-26 09:26 UTC, RomanDubovskyi approved these changes

2021-01-26 09:50 UTC, merged