HM_dao5
grom4er/taxi_service pull request #4
Opened 2021-01-14 15:21 UTC by grom4er

Create, fill and test with jdbs DAO

2021-01-14 15:31 UTC, Ketch92 requested changes

2021-01-14 15:31 UTC, Ketch92 commented on src/main/java/taxiservice/dao/jbdc/ManufacturerJdbcDaoImpl.java
> +                throw new RuntimeException("");
you can move this throw to the very end of the method and remove else part

2021-01-14 15:31 UTC, Ketch92 commented on src/main/java/taxiservice/util/ConnectionUtil.java
> +        }
why is it empty?

2021-01-15 07:09 UTC, boroda4436 requested changes

2021-01-15 07:09 UTC, boroda4436 commented on src/main/java/taxiservice/dao/jbdc/ManufacturerJdbcDaoImpl.java
> +                + "(manufacturer_name, manufacturer_country) VALUE (?, ?)";
```suggestion
                + "(name, country) VALUE (?, ?)";
```
you already know that this is manufacturer

2021-01-15 16:27 UTC, boroda4436 approved these changes

2021-01-15 16:27 UTC, boroda4436 commented on src/main/java/taxiservice/resources/initDB.sql
> +CREATE DATABASE `Taxi_service`;
```suggestion
CREATE DATABASE `taxi_service`;
```

2021-01-18 08:06 UTC, merged