HM_dao8
grom4er/taxi_service pull request #9
Opened 2021-01-21 10:19 UTC by grom4er

2021-01-21 10:35 UTC, Resci requested changes

2021-01-21 10:35 UTC, Resci commented on src/main/webapp/web.xml
> +        <url-pattern>/cars/add_driver_to_car</url-pattern>
Bad naming. Check [checklist](https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/08_servlets_practice_checklist.html)

2021-01-21 10:35 UTC, Resci commented on src/main/java/taxiservice/controllers/cars/AddDriverToCarController.java
> +        String driverID = req.getParameter("driverID");
You need this variables?

2021-01-21 10:57 UTC, Resci approved these changes

2021-01-21 17:03 UTC, dmytro-hryhoruk requested changes

2021-01-21 17:03 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/controllers/cars/CreateCarController.java
> +        String manufactureId = req.getParameter("manufacture id");
```suggestion
        String manufactureId = req.getParameter("manufacture_id");
```
This parameter's name is different from the one in jsp. So it doesn't work. Let's test code before commiting it
![image](https://user-images.githubusercontent.com/50640794/105384569-0e605a00-5c1b-11eb-8496-1bd18dcdbe08.png)

2021-01-21 17:03 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/controllers/cars/CreateCarController.java
> +        String manufactureId = req.getParameter("manufacture id");
check this everywhere

2021-01-21 17:03 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/index.jsp
> +  </form>
It doesn't work too

2021-01-22 09:41 UTC, dmytro-hryhoruk approved these changes

2021-01-23 13:21 UTC, merged